---
- name: Gather installed helm version, if there is any
  ansible.builtin.shell: helm version
  register: helm_result
  failed_when: helm_result.rc != 0 and helm_result.rc != 127
  # Since this is a reporting task, it should never change
  # as well run and register a result in any case
  changed_when: false
  check_mode: false

- name: Install Helm
  ansible.builtin.shell: |
    curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    chmod +700 get_helm.sh
    ./get_helm.sh
  when: helm_result.rc != 0

- name: Install kubectl
  ansible.builtin.shell: |
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

- name: Install jq
  ansible.builtin.package:
    name: jq
    state: present

- name: Create directory .kube
  file:
    path: ~{{ ansible_user }}/.kube
    state: directory
    owner: "{{ ansible_user }}"
    mode: "u=rwx,g=rx,o="

- name: Check whether kube config exists
  stat:
    path: ~/.kube/config
  register: kubeconfig_result

- name: Get k3s config
  ansible.posix.synchronize:
    src: rsync://{{ controller_ip }}/home/{{ ansible_user }}/.kube/config
    dest: ~/.kube/config
  when: not kubeconfig_result.stat.exists

- name: Check whether CRDs installed
  ansible.builtin.command: kubectl get crd
  register: crd_register

- name: Run all admin bookstrap scripts
  ansible.builtin.command: >-
      ../chart/admin/logging/scripts/eck_install.sh
  register: addons_init
  when: "crd_register.stdout | length < 16"
  changed_when: true

- name: Install Cert-Manager
  ansible.builtin.command: kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.12.0/cert-manager.yaml
  changed_when: true

- name: Install ingress-nginx
  ansible.builtin.command: helm upgrade --install ingress-nginx ingress-nginx \
  --repo https://kubernetes.github.io/ingress-nginx \
  --namespace ingress-nginx --create-namespace

- name: Output values yaml
  ansible.builtin.template:
    src: k8s-manifest.yaml.j2
    dest: ../chart/{{ project_name }}-values.yaml
    mode: u+rw

- name: d_ocean | helm | deploy btrix
  ansible.builtin.command: helm upgrade --install -f ../chart/values.yaml -f ../chart/{{ project_name }}-values.yaml btrix ../chart/
  register: helm_result
  changed_when: helm_result.rc == 0
  environment:
    KUBECONFIG: "/home/{{ ansible_user }}/.kube/config"
  tags: helm_upgrade
